### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mholyjr** [mholyjr/hire-ai#1]
- [x] set candidate to NO YES MAYBE
- [ ] Print candidates detail
- [x] Download source CV pdf
- [x] Stripe
- [x] Landing page
- [ ] Filters to positions list
- [ ] state switch to candidate detail
- [x] edit candidate data
- [ ] fix updating position info
